export const bountyData = [
  {
    header: true,
    name: 'NAME',
    type: 'TYPE',
    Difficulty: 'DIFFICULTY',
    amount: 'AMOUNT',
  },
  {
    header: false,
    name: 'KGB#110',
    type: 'FE',
    Difficulty: 'Expert',
    amount: '$90',
  },
  {
    header: false,
    name: 'KGB#111',
    type: 'FE',
    Difficulty: 'Intermediate',
    amount: '$40',
  },
  {
    header: false,
    name: 'WKM#187',
    type: 'BE',
    Difficulty: 'Intermediate',
    amount: '$200',
  },
  {
    header: false,
    name: 'WKM#188',
    type: 'BE',
    Difficulty: 'Expert',
    amount: '$250',
  },
  {
    header: false,
    name: 'WKM#387',
    type: 'BE',
    Difficulty: 'Expert',
    amount: '$300',
  },
  {
    header: false,
    name: 'KGB#111',
    type: 'BE',
    Difficulty: 'Expert',
    amount: '$900',
  },
  {
    header: false,
    name: 'KGB#1191',
    type: 'DevOps',
    Difficulty: 'Intermediate',
    amount: '$80',
  },
  {
    header: false,
    name: 'WKM#107',
    type: 'Design',
    Difficulty: 'Intermediate',
    amount: '$200',
  },
  {
    header: false,
    name: 'WKM#189',
    type: 'FE',
    Difficulty: 'Expert',
    amount: '$450',
  },
  {
    header: false,
    name: 'WKM#3870',
    type: 'BE',
    Difficulty: 'Expert',
    amount: '$3000',
  },
];
